### ISSUE TITLE
Wifi Station mode

### ISSUE THREAD

**Issue by bknill** [sybond/MiSphere-hack#1]
Have you had a chance to look at putting the Mi Sphere in station mode? 

It was pretty easy on the Xiaomi Yi 4k 

https://github.com/irungentoo/Xiaomi_Yi_4k_Camera/tree/master/4k%2B/wifi

Probably similar on this device.

Also any luck with the Bluetooth commands?

**Comment by sybond** [comment]
For Mi Sphere i think the station mode can be achieved using [wifi.conf](https://github.com/sybond/MiSphere-hack/blob/master/firmware/pref/wifi.conf) configuration.

Change `WIFI_MODE` into `sta`.
```
# ap: SoftAP mode
# sta: Station mode
# p2p: Enable Wifi Direct Support for peer-to-peer connectibity
WIFI_MODE=ap
```
Anyway, I didn't have chance to check it, whether the config working or not. Also about other to-do, currently on hold since I don't have the Mi Sphere BT remote device. I have tried whith 3rd party remote, it just don't work (able to pair, but not function).

**Comment by bknill** [comment]
Sorry yes you did awesome thanks! I'll test it.
